### ISSUE TITLE
Ruby Client - Read methods

### ISSUE THREAD

**Issue by luke-hill** [railsware/mailtrap-ruby#31]
I've looked on the repo and I cannot find any sort of Ruby API to perform reading of boxes

I'm aware issues are usually for bugs e.t.c. - But to me this feels like either something that doesn't exist or I haven't found it.

For reference I have previously used [mailosaur](https://mailosaur.com/docs/languages/ruby?utm_source=21293812759--&gad_source=1&gclid=Cj0KCQiAi_G5BhDXARIsAN5SX7pcGn27R7sIXapctciY-YLNo3MF6Tl8j_Yi0K2qtOxvnkB3_YFjX6AaAje_EALw_wcB) at several companies, but we pay for mailtrap here. So I was hoping to find an API to read emails. I'm expecting to do something like this.

```
client = MailTrap::Emails::Client.new
subject_emails = client.emails(subject: 'Only return emails with this subject')
date_emails = client.emails(received_before: DateTime.new(2024-11-19))
```

Then I'm expecting something like

```
p subject_emails.first.text
p date_emails.first.attachments.length
```

Please advise?

**Comment by i7an** [comment]
Hi,

Currently, this gem only provides a unified interface for the **Sending API**, allowing you to send test emails to an inbox in development and real emails in production.

Unfortunately I don't think we support the requested functionality out of the box. I'll try to find out if it is planned or not and get back to you.

I know that this is not what you asked for, but accessing the Mailtrap API should be fairly straightforward using Faraday or a similar library.

```ruby
connection = Faraday.new('https://mailtrap.io/api/accounts/1234') do |f|
  f.request :authorization, 'Bearer', '********48db'
  f.request :json
  f.response :json
end
# https://api-docs.mailtrap.io/docs/mailtrap-api-docs/a80869adf4489-get-messages
response = connection.get('inboxes/5678/messages', search: 'welcome')
response.body # => [{"id" => 1, ...}, {"id" => 2, ...}]
```

**Comment by i7an** [comment]
This is the first request like that for the Mailtrap Ruby library. Dealing with limited resources, we have to prioritize features. Your request has been registered, but the likelihood of it being implemented **quickly** is not high.

> ...If it's ok with you let's keep this open for a while  ... probably early 2025 ...

We try to resolve issues quickly. This is one of the metrics. That's why I'm going to close the issue. Sorry about that.

As you approach integration next year, please feel free to contact us here or through our support. We are always happy to help! 🤓
