### ISSUE TITLE
Can't send "from" an email containing brackets

### ISSUE THREAD

**Issue by ghiculescu** [railsware/mailtrap-ruby#32]
We are seeing errors in production when sending email via Mailtrap where the `from` address includes brackets. For example

```ruby
mail(from: "foo (bar) <email@example.com>")
```

Leads to this

![image](https://github.com/user-attachments/assets/e5e348d5-553d-4904-8213-27e5af8e5528)

I tried writing a failing test, I couldn't get it to crash, but it does fail:

```diff
diff --git a/spec/mailtrap/mail_spec.rb b/spec/mailtrap/mail_spec.rb
index 6bd5f88..301d545 100644
--- a/spec/mailtrap/mail_spec.rb
+++ b/spec/mailtrap/mail_spec.rb
@@ -13,7 +13,7 @@ RSpec.describe Mailtrap::Mail do
     let(:message) { Mail::Message.new(**message_params) }
     let(:message_params) do
       {
-        from: 'Mailtrap Test <mailtrap@mailtrap.io>',
+        from: 'Mailtrap (Test) <mailtrap@mailtrap.io>',
         to: 'To 1 <to_1@railsware.com>, to_2@railsware.com',
         cc: 'cc_1@railsware.com, Cc 2 <cc_2@railsware.com>',
         bcc: 'bcc_1@railsware.com, bcc_2@railsware.com',
@@ -23,7 +23,7 @@ RSpec.describe Mailtrap::Mail do
       }
     end

-    its(:from) { is_expected.to eq({ name: 'Mailtrap Test', email: 'mailtrap@mailtrap.io' }) }
+    its(:from) { is_expected.to eq({ name: 'Mailtrap (Test)', email: 'mailtrap@mailtrap.io' }) }
     its(:to) { is_expected.to eq([{ name: 'To 1', email: 'to_1@railsware.com' }, { email: 'to_2@railsware.com' }]) }
     its(:cc) { is_expected.to eq([{ email: 'cc_1@railsware.com' }, { name: 'Cc 2', email: 'cc_2@railsware.com' }]) }
     its(:bcc) { is_expected.to eq([{ email: 'bcc_1@railsware.com' }, { email: 'bcc_2@railsware.com' }]) }
```

![image](https://github.com/user-attachments/assets/85f8c8a8-986d-46e2-972b-fcb28b7bc86f)

So I suspect there's something wrong in the gem here, and maybe the test just isn't accurately replicating how Action Mailer works.

**Comment by leonid-shevtsov** [comment]
You should quote the display name if it contains parenthesis, they are a special character according to the [RFC](https://www.rfc-editor.org/rfc/rfc5322#section-3.4); the relevant part is:

```
display-name = phrase
phrase          =   1*word / obs-phrase
word            =   atom / quoted-string
atom            =   [CFWS] 1*atext [CFWS]
atext           =   ALPHA / DIGIT /    ; Printable US-ASCII
                       "!" / "#" /        ;  characters not including
                       "$" / "%" /        ;  specials.  Used for atoms.
                       "&" / "'" /
                       "*" / "+" /
                       "-" / "/" /
                       "=" / "?" /
                       "^" / "_" /
                       "`" / "{" /
                       "|" / "}" /
                       "~"
```

Or you can use the email+name form, and I'm pretty sure we will quote it for you:

```
{ email: 'mailtrap@example.com', name: 'Mailtrap (Test)' }
```

But I admit that stripping the parens is sketchy, will look into it.

**Comment by leonid-shevtsov** [comment]
Ah, even more interesting - from the same RFC - is that contents of the parens are considered _comments_. Fascinating!

>Also, strings of characters that are treated as comments may be included in structured field bodies as characters enclosed in parentheses.

https://www.rfc-editor.org/rfc/rfc5322#section-3.2.2

**Comment by leonid-shevtsov** [comment]
However it seems that the actual cause of your error is an empty `From` header. Looking at the code, I don't see other possible ways to reproduce.

PR with better error message incoming.

**Comment by i7an** [comment]
@ghiculescu I believe invalid email address caused the error for you. I'll work on the fix.

**Comment by ghiculescu** [comment]
This script confirms that your fix fixes that crash, if the `from` is blank.

```ruby
require "bundler/inline"

gemfile(true) do
  source "https://rubygems.org"

  gem "rails", path: "/Users/alex/code/rails" #github: "rails/rails", branch: "main"
  gem "mailtrap", "2.1.1"
end

require "action_mailer/railtie"
require "minitest/autorun"

class TestApp < Rails::Application
  config.load_defaults Rails::VERSION::STRING.to_f
  config.root = __dir__
  config.eager_load = false
  config.hosts << "example.org"
  config.secret_key_base = "secret_key_base"
  config.logger = Logger.new($stdout)
end

require "mailtrap/action_mailer"
::ActionMailer::Base.add_delivery_method(:mailtrap, Mailtrap::ActionMailer::DeliveryMethod)
ENV["MAILTRAP_API_KEY"] = "test"

class TestMailer < ActionMailer::Base
  def hello_world
    @message = "Hello, world"
    mail from: "", to: "user@example.com", delivery_method: :mailtrap do |format|
      format.html { render inline: "<h1><%= @message %></h1>" }
      format.text { render inline: "<%= @message %>" }
    end
  end
end

class BugTest < ActionMailer::TestCase
  test "renders HTML and Text body" do
    email = TestMailer.hello_world
    email.deliver_now
  end
end
```

But I'm really really sure it wasn't blank in my case... let me try and get a working replication.

**Comment by ghiculescu** [comment]
> I believe invalid email address caused the error for you

Yep... this is it.

This `from` works fine: `"foo (bar) <example@example.com>"`. This crashes: `"foo bar) <example@example.com>"`. It seems like your commit has fixed the crash, so thank you!

**Comment by i7an** [comment]
@ghiculescu I've just pushed a new version `2.1.2`. It includes the improved error handling for invalid emails.
